#!/bin/bash
#
# name: workrecord
# description: records working time to an csv file
# author: Tommy Schmucker
# created: 2021-10-01
# version: 0.1.0
#
# arguments order:
#		DATE in format DD.MM.YYYY (can be omitted, default today)
#		HOURS float
#		PROJECT
#		COMMENT
# example: $ bash workrecord 24.12.2021 3.5 XMAS "preparing cakes"
#

FILE=timetable.csv
HEADER="date,hours,project,comment"
REGEX="[0-9]{2}.[0-9]{2}.[0-9]{4}$"
DATE=$(date '+%d.%m.%Y')
HOURS=0
PROJECT="not specified"
COMMENT=""

if [ ! -f "$FILE" ]; then
	echo "$FILE does not exist..."
	echo "creating..."
	echo "$HEADER" > "$FILE"
	echo "...done"
fi

while test $# -gt 0; do
	if [[ $1 =~ $REGEX ]]; then
		DATE=$1
		shift
	fi
	HOURS=$(echo "$1" | tr ',', '.')
	shift
	PROJECT=$1
	shift
	COMMENT=$1
	shift
done

echo "\"$DATE\",$HOURS,\"$PROJECT\",\"$COMMENT\"" >> "$FILE"

echo "Recorded a new entry..."
echo "Date: $DATE"
echo "Hours: $HOURS"
echo "Project: $PROJECT"
echo "Comment: $COMMENT"

exit 0

